apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deploy
  labels:
    app: dev
spec:
  replicas: 5
  selector:
    matchLabels:
      app: dev
  template:
    metadata:
      labels:
        app: dev
    spec: 
      terminationGracePeriodSeconds: 1
      containers:
      - name: hello-pod
        image: ietvijay/hello-world-web:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080