apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deploy
  labels:
    app: dev
spec:
  selector:
    matchLabels:
      app: dev
  replicas: 5
  minReadySeconds: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: dev
    spec: 
      terminationGracePeriodSeconds: 1
      containers:
      - name: hello-pod
        image: ietvijay/hello-world-web:v2
        imagePullPolicy: Always
        ports:
        - containerPort: 8080